#!/usr/bin/env bash
#Using IFS for the fisrst time
while IFS=':' read -r username group_id home_directory shell uid password info; do
	echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
