#!/usr/bin/env bash
#Using ifs for the first time
while IFS=':' read -r USERNAME PASSWORD USER_ID GID USER_INFO HOME COMMAND; do
    echo "The user $USERNAME is part of the $GID gang, lives in $HOME and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < /etc/passwd

