#!/usr/bin/env bash
#writing a clock script

hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    #initializing the  minute variable
    minute=1
    while [ $minute -le 59 ]; do
	    echo "$minute"
	    minute=$((minute + 1))
	   done
	   hour=$((hour + 1))
done
