#!/usr/bin/env bash
#this script removes the hyphen
for file in *; do
#skipping the hidden files
  [[ "$file" == .* ]] && continue
  if [[ "$file" == *-* ]]; then
    echo "$file" | cut -d '-' -f2-
else
      echo "$file"	
  fi
done
