#!/usr/bin/env bash
#This script will manage a process

PID_file="/var/run/my_process.pid"
process="./manage_my_process"

#Creating the start function
start() {
	$process &
	echo $! > "$PID_file"
	echo "manage_my_process started"
}

#Creating the stop function
stop() {
	if [ -f "$PID_file" ]; then
		kill "$(cat "$PID_file")"
		rm -f "$PID_file"
		echo "manage_my_process stopped"

	else 
		echo "manage_my_process is not running"
	fi
}

#Creating the restart function to restart the process
restart() {
	stop >/dev/null
	start >/dev/null
	echo "manage_my_process restarted"
}

case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
